#!/bin/bash

# EwsgitOS (c) 2022 Ewsgit
# Do not edit this file as it will be reset in future updates. instead edit the file custom.sh in "~/.bash/"

export PS1="[EwsgitOS|$user]"

# import the custom terminal startup banner
source "~/.bash/startup_banner.sh"

# import the custom powerline (PS1)
source "~/.bash/powerline.sh"

# import aliases made using the alias tool
source "~/.bash/aliases.sh"
